version: '3'

services:
  db:
    image: onjin/alpine-postgres:9.5
    restart: unless-stopped
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: hellofresh
      POSTGRES_USER: hellofresh
      POSTGRES_PASSWORD: hellofresh

  server:
    build: .
    command: python scripts/create_schema.py && python server.py
    environment:
      - DATABASE_URL=postgres://hellofresh:hellofresh@db/hellofresh
    volumes:
      - ./:/app
    links:
      - db
    ports:
      - "8080:8080"
