version: '3'

services:

  redis:
    image: sickp/alpine-redis:3.2.2
    restart: unless-stopped

  server:
    build: .
    volumes:
      - ./:/app/web
    links:
      - redis
    ports:
      - "8080:8080"
