version: '3'

services:

  redis:
    image: sickp/alpine-redis:3.2.2
    restart: unless-stopped

  python:
    image: python:3.6
    volumes:
      - ./:./web
    links:
      - redis
    ports:
      - "8080:8080"
