version: '3'

services:
  python:
    image: python:3.6
    environment:
    - DEBUG: 'true
          - PORT: '8080'
    volumes:
    - ./:/server/http
    links:
    - postgres
    - mongodb
    - redis
    ports:
    - "8080:8080"

  redis:
    image: sickp/alpine-redis:3.2.2
    restart: unless-stopped
    ports:
    - "6379:6379"

